export type TextTestimonial = {
  name: string;
  text: string;
  photo: string;
  tags: string[];
  publishedAt: string;
};

export const TEXT_TESTIMONIALS: TextTestimonial[] = [
  {
    name: "Arthur Marques",
    text: "Demorei para avaliar pq estava ocupado dormindo! Simplesmente curou minha insônia, o que dizer alêm de maravilhoso? Atendimento nota 1000 e médicos super atenciosos, tive uma boa experiência com eles.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXPouVB9i7UvB05rFF5QtGH32AyCz_xxS5MlwQQVHFZYr7bwWwa=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2024-08-01",
  },
  {
    name: "Verista Convicto",
    text: "Estou tomando pra ansiedade e tem me ajudado muito. No começo fiquei meio receoso, mas é um ótimo produto, não causa nenhum barato, é totalmente seguro. Não tive qualquer efeito colateral. Hoje durmo melhor.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUFUHpBX3tRXzZCyEMEvkheDK-1zTzBrX44yeyMwG_YHycxg9fG=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2024-04-05",
  },
  {
    name: "Nath Gomes",
    text: "Mesmo com pouco tempo de tratamento já tenho observado uma grande melhora na minha qualidade de sono e diminuição das crises de ansiedade.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWn39k1vGabrkl8lrp3d3Xz03mZD3AtBreXtnYW1K5X5HgdZFQ-Tw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2024-04-06",
  },
  {
    name: "Jhonat Anschau",
    text: "O Atendimento é ótimo, dão atenção total. Quanto aos efeitos são significativos, logo nos primeiros dias senti uma melhora no humor, mais ânimo diurno, e o fim das insônias. Após uns 45 dias alteramos as dosagem para reequilibrar, mas sempre com acompanhanto. Demonstraram interesse, atenção e profissionalismo.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVVNJyfIcnUVY8vYk_NH3Ke-WtsIpQq6SeiGL4V120nyUxxQ4rY=s96-c-rp-mo-br100",
    tags: ["Insônia", "Humor"],
    publishedAt: "2025-05-19",
  },
  {
    name: "Verinha Azeredo",
    text: "Olá, boa noite! Estou muito satisfeita com o tratamento que iniciei na última 4a-feira (28/ago), e nítida a chave emocional que virou dentro de mim. Voltei a dormir e sinto-me bem relaxada após iniciar a minha medicação de CBD. Gratidão a todos vocês. Vera Lucia Teixeira de Azeredo",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVFFlhouybjbHsZQFaixaiNmIw-QPwHTbKw1g6kEdmdVfKR-F-PYw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Humor"],
    publishedAt: "2025-07-16",
  },
  {
    name: "Juliana Leal",
    text: "Excelente atendimento e serviço! Estou amando meu tratamento com cannabis. Uso Zolpiden há 10 anos para insonia e agora finalmente consegui me livrar desse remédio com tantos efeitos colaterais porque o óleo de cannabis salvou minha vida curando a insônia! Obrigado ClickCannabis",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWNS0avSn4zNm0g6fP1ToknkN2VEFgiD4zvmsnVSvG6-Q7VaAQs=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2024-04-27",
  },
  {
    name: "Duda Santana",
    text: "Tenho sentido os efeitos benéficos da Cannabis para o meu tratamento de Insônia, TAG, TDAH e dor crônica da Endométriose. Simplesmente recomendo muito. Principalmente a equipe da Click Cannabis que tem dado todo o suporte necessário :)",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVJ_LVKIu6ZgrXYAbvIP1y_pE2pqJg89SlgPgXrumc169z-o3jcLw=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Ansiedade", "Dor"],
    publishedAt: "2025-02-10",
  },
  {
    name: "Jorge Moreira",
    text: "A melhor possível ,tudo dentro da lei e no que eu estava precisando os óleos estão me auxiliando demais, peguei um pra regularizar o meu sono e um pra tentar para de fumar Resultado positivos em apenas três dias.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVHYZMKG_LytwrDqQCkzZuslwAn3LmAO64zd8uuSPXMw1s_jq2M=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-07-16",
  },
  {
    name: "Luciana Pereira",
    text: "Desde o primeiro momento, muito bem atendida! Com 30 dias em uso do óleo, melhorou a qualidade do meu sono e já não me sinto tão ansiosa quanto antes do tratamento! Grata à Click cannabis! 💚",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUiAJcs-Is_zgYWF7mHzAbbGeHNkhrX5gLFjWu9FtUGMwzTlmR1=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-05-26",
  },
  {
    name: "Didi da Silva",
    text: "Sofro com insônia, ansiedade e depressão. Recorri a Click Cannabis como forma de deixar o Rivotril e ter uma melhor qualidade de sono. Está sendo uma experiência e tanto, desde que comecei o tratamento, meu sono melhorou consideravelmente, mesmo reduzindo a quantidade de Rivotril. Indico muito. Só tenho a agradecer.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLwAgJQ1Wi9G8EZllSXQehsAArH7hbaLMuq5z26SFnW6PbrRQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Depressão"],
    publishedAt: "2025-10-02",
  },
  {
    name: "ILZA CRISTIANE CARDOZO",
    text: "Eu conheci a clínica através de uma amiga. Comecei meu tratamento hoje, mas na primeira dose já senti uma melhora. Eu trato depressão há quatro anos. Tenho muita crise de ansiedade. Faz dois meses que faço tratamento, não tive mais crise de ansiedade. Quanto a insônia tenho que testar nao tomar os outros para saber.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVa7AcHRDRvJ3kWbZfpzbI6G5jomWeQwjtE9YS5jgAtG_aCfbWLDA=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Depressão"],
    publishedAt: "2026-03-06",
  },
  {
    name: "Gislene Spelta",
    text: "Estou gostando muito , meu sono melhorou bastante ( agora consigo pegar no sono rapidamente), as dores não passaram mas posso dizer que diminuíram por volta de 50% , o que é um grande avanço pra mim. Resumindo , dormindo melhor e com menos dores posso dizer que estou feliz e que consigo me sentir mais viva agora.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocJ3pCvGFz5O9jqx9zaWlsrbTsmxq-gnx1qhuN1Tt8pl-ioNXQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2025-09-27",
  },
  {
    name: "Angela Nicolau",
    text: "Comecei o tratamento a um pouco mais de 7 dias. Insônia crônica pela menopausa a 6 meses. Na primeira noite, já senti melhora na qualidade do sono. Ajustando a dose, conforme prescrição, hoje durmo às 22:30h e acordo às 6h. Não há preço que pague isso. Obrigado a Click e a todos os envolvidos. Angela Nicolau",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXeUZ6pk_QyGqdRglIrJrRjAMYBvBuagiKhxJx5ClF5hBQ_zYmVUw=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-11-26",
  },
  {
    name: "Suze Costa",
    text: "Faz um mês que faço uso da cannabis, posso dizer que minha ansiedade zerou e a insônia que me incomodava muito, hoje não tenho mais. Com 20 dias de uso, aboli o rivotril e o sono é gostoso e satisfatório, quando acordo de madrugada é só fechar os olhos e adormeço novamente. Gratidão a todos da equipe!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVcfJ0sbQJD50ek-u1bxUpm5H7PlV0rWfrtrepYWplYO5PdOnvSzA=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-05-08",
  },
  {
    name: "Rosilda Costa",
    text: "Depois 30 dias sentir uma melhora nas minhas dores do joelho que tenho devido a artrose. Tenho sentido menos ansiedade. O sono ainda tá melhorando dias sim durma bem dias sim não..Mais creio que é devido preocupações do dia a dia. No mais eu indico quem puder comprar pq acho caro.mais tá compensando",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjV8EvbDrxXexHjs-Us71esqNXeXVcaWnBNSLbIipuhkltNFyx9WKQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Artrite"],
    publishedAt: "2025-12-07",
  },
  {
    name: "françoise Alves",
    text: "Um mês de click e finalmente consigo sentir alívio para dormir e esperança que estou no caminho certo, a fibromialgia é dura, mas agora consigo ter esperança que em breve a qualidade de vida vai ficar 100% de novo. Muito boa a empresa, atenciosa e super atenta as nossas dificuldades, recomendo demais",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLb6NeT956T3jbLQO3e1zNNIZTFUYQIv_Lcx5EAj38LmpdfpA=s96-c-rp-mo-br100",
    tags: ["Insônia", "Fibromialgia"],
    publishedAt: "2025-10-01",
  },
  {
    name: "Ana Paula Machado de Melo",
    text: "Estou me sentindo muito bem. Nao tenho mais dores na coluna. Durmo a noite toda. Esse óleo de canabidiol é muito bom. Podem comprar sem medo. O valor vale muito a pena. Comprarei mais. Minha vida mudou bastante pois tinha dores constantes , muita ansiedade, e insônia. Tudo melhorou.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWalNwlwkahdtWQzeDzEeQybK-SRq5ltQJN_Ne3yaqk0tJBL0_tpA=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Dor na coluna"],
    publishedAt: "2026-03-31",
  },
  {
    name: "KA Brasil",
    text: "“Estou usando as gotinhas de CBD da Click Canabis há 15 dias e os resultados têm sido fantásticos! Meu sono melhorou significativamente e meus dias estão muito mais produtivos. Fiquei impressionado com a qualidade do atendimento e a total transparência em todo o processo. Recomendo!”",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVR22rDBhC7Nh8aegoTpwU50E6sYvfR9vKR394i4CFAYmWAPA8f=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2026-04-01",
  },
  {
    name: "Fabio Santos",
    text: "Me chamo Fabio tenho 53 anos e estou usando a pouco tempo (12 dias),mas ja sinto diferença na qualidade do meu sono e um alivio em minhas dores por conta da artrose no joelho e da estenose lombar. E o suporte da empresa click cannabis e da transportadora tre star express sao nota 10",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUHy-_5tvHfHhmvPfVOKKWZI1sD3xHc1TEGuM_kC3rG1zLcjTVo=s96-c-rp-mo-br100",
    tags: ["Insônia", "Artrite", "Dor na coluna"],
    publishedAt: "2026-04-28",
  },
  {
    name: "Mirna Ribeiro",
    text: "Apenas 15 dias e já durmo bem, minha respiração não fica ofegante quando eu sinto que vou ter a crise de ansiedade. Na verdade, quando senti que ia ter, consegui me acalmar tomando algumas gotas a mais conforme me foi auxiliado. Indico muito, estou realmente muito satisfeita!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVS3Ig_3GDdQmKpr3EK1VeSCrNiBQAS2j5Dt9dHj_6y4U92B6na3A=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Pânico"],
    publishedAt: "2026-04-01",
  },
  {
    name: "Juliana Lopes",
    text: "Mudou a minha vida , sou Autista suporte 1e AHSD, em um mês , meus tremores das mãos pararam , minha ansiedade reduziu muito , qualidade do sono … também mantenho uma rotina de alimentação e atividades físicas ! Melhorou muito a minha constância nessas e outras atividades.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWmqQ3MmUnlBpqRJb_uXUel2PrcjREUz2s2-PY0w-4PnqIMtHI1=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Tea"],
    publishedAt: "2025-09-18",
  },
  {
    name: "Vanessa Wankler",
    text: "Hoje faz um mês que iniciei o tratamento com canabidiol, não tenho mais crises de ansiedade, meu sono melhorou 100%, acordava em estado de alerta várias vezes por noite, hoje durmo continuamente! Dores nas articulações diminuíram muito! Estou muito feliz com os resultados!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWswlqO_7yZkYcI5hVze16n4xb2pP-LKLGcFGw5I7F0Gv9QJnM=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Ansiedade", "Artrite"],
    publishedAt: "2025-07-16",
  },
  {
    name: "Danilo Mastroianni",
    text: "Estou em fase inicial de tratamento, e venho obtendo bons resultados! Através da Click Cannabis iniciei o tratamento para depressão e insônia com o uso do Óleo Full Spectrum Canna River e está realmente funcionando! Gratidão por tudo que a Click Cannabis fez por mim!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjV6zg9GbeXFror66yPwVNelt12hh80fhNXmm5w3sUH1_Oee7ypp=s96-c-rp-mo-br100",
    tags: ["Insônia", "Depressão"],
    publishedAt: "2025-10-19",
  },
  {
    name: "jordi font",
    text: "Boa tarde, estou muito grato pelo tratamento da insônia com o uso do cannabis,um mês do uso e estou conseguindo dormir melhor sem precisar usar os fármacos que me faziam mal.Gratidao a toda a equipe do click são muito atenciosos acompanhando todo o tratamento.grato",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocL5vy4y6CumZBJpcNThKZ50wO__a39-hFz2WeG-LzGzFW6x8Q=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-04-25",
  },
  {
    name: "marina",
    text: "Estou fazendo uso do óleo á 25 dias, estou bem melhor da ansiedade já estou fazendo o desmame da paroxetina e do alprazolam. A gominha uso só em períodos de insônia, mas quase não uso pq estou dormindo melhor depois de iniciar o tratamento com o óleo de cbd.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocIC_HIW5AJg67DO8Ue-0twvPXbi9F9j0wBrHMpYmzrfYRpXOA=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2026-01-28",
  },
  {
    name: "luiz carlos pizani",
    text: "Gostei demais. Fui muito bem recebido por toda equipe e tive uma excelente consulta médica. Estou tomando a medicação e tenho verificado uma melhora muito grande na qualidade do meu sono e no combate a dores de articulação causadas pela prática de esporte",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLubb3OyMY-mlK8_hcfw2JqIWYUy5sclrpzY-hm2rvIleovNw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2026-04-20",
  },
  {
    name: "Pri Luz",
    text: "Após 20 dias de tratamento com o óleo e a goma, parece que minha mente \"clareou\". Não tive mais crises fortes de ansiedade e meu sono melhorou muito, muito mesmo! Agradeço imensamente a esquipe da Click pelo cuidado, atenção e prontidão no atendimento.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUTB3dat2zf9Jz10_EaWOZXXCkDMp7cSfkyIlxrh02Y0llr_o6gHQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Foco"],
    publishedAt: "2026-03-30",
  },
  {
    name: "Thiago Jattobá",
    text: "Excelente e rápido atendimento. Consulta com preço muito acessível e o valor da medicação é bem menor que os tarja pretas. Hoje completo minha primeira semana de tratamento e já sinto menos ansiedade, melhoria na qualidade do meu sono e melhor apetite!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUA-_QcyYK0KEvH2yot8Lv6XbolCfOkTx6dlFoPnj3j7hqjmmIO3Q=s96-c-rp-mo-ba3-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-01-21",
  },
  {
    name: "Maria Helena Rodrigues",
    text: "olha. estou tomando há menos de um mês. Teve uma noite q dormi muito bem como não dormia há muito tempo, porém ainda tomoantidepressivo e remédio pra dormir...então não se mensurar direiro o efeito do óleo. Queria mesmo é parar de tomar tanto remédio.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjV4m3lJ0rkgedtUEmmaDCKonJwhRn8d4fplSw0Nc5Li1S21JErb=s96-c-rp-mo-br100",
    tags: ["Insônia", "Depressão"],
    publishedAt: "2026-02-24",
  },
  {
    name: "Lorena Carvalho da Silva",
    text: "Recomendo muito! Estou tendo resultados em menos de 2 meses. Não estou tendo crises de ansiedade e a insônia foi embora. Estou muito feliz! O atendimento médico e suporte administrativo são maravilhosos. Estão sempre dispostos a ajudar e tirar dúvidas",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWYqgYrRdQxiffO1KV8e_ggKjBLOOtzQGMFpoUUc2ny8qYHnYuN=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Pânico"],
    publishedAt: "2025-09-19",
  },
  {
    name: "Cyco Engel",
    text: "Muito boa a interação com a click cannabis, ótimo atendimento e suporte. Meu tratamento completou 1 mês, tenho síndrome pós-pólio, o que me provoca dores crônicas nas articulações e insônia, com o tratamento minha qualidade de vida melhorou em 100%",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVo4t6eF69gATFZrVjMXN3kS6d07rbBX0QdUdPAfXoLYPX6xLIEwA=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2025-09-18",
  },
  {
    name: "carmen feix",
    text: "Atendimento atencioso, cordial, eficiente e ágil. A medicação chegou em 1 semana. Eu estou em tratamento há 15 dias e já sinto os efeitos positivos. Enxaqueca cedeu, mais tranquilidade, sono ok, e redução de 3kg com auxílio do THCV. Recomendo!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVv8H2Z9BXw2_O-g6--azz86vHKf1tYy6SnH8cbpL9bIsZGodWVMw=s96-c-rp-mo-ba3-br100",
    tags: ["Insônia", "Ansiedade", "Enxaqueca"],
    publishedAt: "2025-12-16",
  },
  {
    name: "Mayara de Lucca",
    text: "Primeiro mês fazendo o tratamento com canna river e estou simplesmente sem crises de pânico, ansiedade. Durmo bem, acordo bem e ainda tenho disposição durante o dia. Isso me salvou muito, eu não fazia ideia dos benefícios. Agora eu não fico sem",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocJzdmvHsXTtw9FPZhu6BNn0ETbubpl5hk4jcrMZ-KEQC4ClPQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Pânico"],
    publishedAt: "2025-06-30",
  },
  {
    name: "Fátima Daoualibi",
    text: "Vi o anúncio num ônibus e entrei em contato. Foi uma experiência que eu quero repetir outras vezes, todos que me atenderam foram excepcionais. O processo é 100% legal e o resultado maravilhoso. Voltei a dormir a noite toda e acordo descansada.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVmKWeqksAfO9sj1_I-_QXetkwlZBPt0ZPKzqQyYXvoGRlTZ2EG=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2024-05-18",
  },
  {
    name: "Aldinei Machado",
    text: "Ótima , medicamento muito bom ,as pessoas super educadas e atenciosas, faz 30dias que estou usando medicamento da click .estou me sentindo muito bem no sono no apetite nas dores, mente super tranquila , menos ansiosa estou gostando muito",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXGhrBF69t_E5Q59C83LPLNr611st2ssZ7nTDcSxT3lqVZs_SJT=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Dor"],
    publishedAt: "2025-05-09",
  },
  {
    name: "Leder Masselai",
    text: "Logo nos primeiros dias já senti melhora na ansiedade e nas dores na coluna causadas pela artrose. Depois de um mês de tratamento posso afirmar que tive umas melhora de 80% nos sintomas, fora o sono com noites tranquilas e reparadoras.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVW3T_GbtjQe0zlUIPpCd5MPZGn6uPDZ3RgacNGnjHUaTNuFMlf=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Artrite"],
    publishedAt: "2025-12-23",
  },
  {
    name: "Carolina Borne",
    text: "A consulta e o acompanhamento da importação foram excelentes, mas não senti diferença nenhuma com a dosagem recomendada. Durante o dia funciona mais ou menos, mas continuo acordando no meio da noite e não consigo voltar a dormir... 🥹",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXVflT-Lat2o_8jIYmRID5hP8R01bivvRvWp4eM_h1jZck2wWQR=s96-c-rp-mo-ba3-br100",
    tags: ["Insônia"],
    publishedAt: "2026-04-02",
  },
  {
    name: "Miguel Menezes",
    text: "Atendimento excelente! Iniciei meu tratamento há um mês e já consigo notar a melhora na minha qualidade de vida. Hoje, fumo menos, durmo melhor e acordo mais disposto! Vejo que já estou próximo do meu objetivo que é parar de fumar.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXoyEb-akP2s5JtR4z5Wf1lyy9Zdg7l5z5AjNA0vBfPMlFz45ll5g=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2024-05-16",
  },
  {
    name: "Adriana Monteiro Lopes Buono",
    text: "O processo com a Click Cannabis tem sido fácil, descomplicado e super profissional desde o início. Adorando. Após um mês de uso do full spectrum senti melhora significativa na qualidade de sono e no humor e a cada dia só melhora.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocJW47hRcwgjKF9_u7-yvaH9WgXC5NEr2uFnNHNo65b7f59uyw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Humor"],
    publishedAt: "2025-07-07",
  },
  {
    name: "Vera Oliveira",
    text: "Boa Noite !! Hoje faz um mês que estou tomando este medicamento,comecei com 2 gotas, por orientação aumentei,hoje estou tomando 5 gotinhas, e já estou vem resultado, na ansiedade e para dormir, vou seguir com este o tratamento.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVH110wNZ6mcSVUmzaeNpKEbyJH3s4Rs56gWnXm0JzMZn5QQSHZ8g=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-05-12",
  },
  {
    name: "Marcilene Cardoso",
    text: "Estou muito satisfeita e aliviada. Minhas dores diminuíram significativamente. Tenho fibromialgia e consegui voltar a realizar coisas da rotina sem entrar em sofrimento. O sono também regularizou. Ganhei qualidade de vida.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLYrpHzfZj9lw9c9lYt1VqzKCEnSW_SX3YzXSeeviMbMXl8FA=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor", "Fibromialgia"],
    publishedAt: "2026-02-23",
  },
  {
    name: "Charles Alves",
    text: "Minha experiência com click está sendo maravilhosa só em deixar de tomar vários comprimidos que eu tomava já foi ótimo agora é só umas gotinhas e fico menos ansioso com mais facilidade para dormir, adorei canabis é vida!.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjU1yuhM9tm3B8n1KpXqeQdlY_dhMMQ3oFwsRPg_YSJKk1whXjBJ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2026-02-02",
  },
  {
    name: "Denise Justino",
    text: "Estou muito feliz, no início eu fiquei receosa sobre valor da consulta porém, o suporte e valores são justos, o medicamento mudou meu dia a dia, eu literalmente parei de ter oscilação de humor, e passei dormir muito bem.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWYgQF63z7Q_MuyqCGvS3uELlA9nGyqFdb6UlaNXztR5Mi4DeHG=s96-c-rp-mo-br100",
    tags: ["Insônia", "Humor"],
    publishedAt: "2025-10-01",
  },
  {
    name: "Raquel Castro Adv",
    text: "O atendimento foi super rápido e eficaz! A equipe me ajudou em todo o processo de compra do medicamento, até o recebimento. Estou utilizando há cerca de um mês e resolveu totalmente meu problema de insônia! Super indico!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXNHuOCkmgdxqZYwDTG0FwIc-o0VfZMvanewk-2cZpAiJuu1EYw=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2024-07-25",
  },
  {
    name: "Sandra CardosoBueno",
    text: "Minha experiência foi muito boa. Após usar a medicação, consegui controlar mais a ansiedade, não estou comendo muito,durmo melhor e sinto um melhor desemprenho no trabalho e atividade física. Estou bem calma.. Obrigada .",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUy_UI7V1cnd4LGAavmK48a3nZg3zn5d_v5Id7gQhHgoEhOXFkj_g=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Foco"],
    publishedAt: "2025-09-12",
  },
  {
    name: "Talita Luciana",
    text: "Já estou na 2ª semana de tratamento e foi a melhor escolha que fiz, estou dormindo a noite toda sem acordar com insônia , me Sinto Mais leve durante o dia e sem ataques de ansiedade, Estou me sentido bem tranquila .",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWN_g5pun0Xd5SKIei_XmesyL49f_4sfHf84b4w96bSoYNIokTo6Q=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-03-06",
  },
  {
    name: "Frederico Guilhon",
    text: "Fazendo uso a uma semana só, observo a musculatura mais relaxada e dores muito menores o que facilita o meu caminhar já sem rigidez e dores quase nenhuma é sono reparador. Tenho sequelas de crises de E.M. Recomendo.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWorCKHNBB9LXu6hNg3sw4lOxGbZE9CsNZxidYiLE2P3okUyc6pGg=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2025-02-21",
  },
  {
    name: "valquiria Barbosa Brant",
    text: "Bom dia! Faz um ano que comecei a ter alguns episódios de insônia, foi quando procurei o atendimento no click Cannabis, estou muito satisfeita com o óleo de cannabis, estou com um sono reparador todos os dias!!🙌",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUtfn49WuI9sLU1cUXQMWeQnmk0YiYVTErZ12hrf2zqf2gOHH0=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-09-17",
  },
  {
    name: "Ana Kokanj",
    text: "Estou em tratamento a 15 dias e sinto uma melhora significativa no sono,sem acordar tanto a noite e voltando a dormir rapidamente qdo deito novamente. Percebo estar com menos dores e menos ansiosa durante o dia.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVIqMQ8H3w1gesvdducL61waKRb8iIRSl4eNHQBfJ1J-rsaE5g=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Dor"],
    publishedAt: "2026-04-06",
  },
  {
    name: "Jacaré Junior",
    text: "Totalmente satisfeito com a Click Cannabis e o medicamento receitado... durmo a noite toda e minha dor na lombar melhorou consideravelmente. Agradeço a todas equipe...foi super rápido todo o processo. Obrigado",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWNArQ_dA1IlEwGCtff03MGSI0aqnTu5c203ZgcWT8CjAK6qEk5fQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor na coluna", "Dor"],
    publishedAt: "2024-04-19",
  },
  {
    name: "Guilherme Lima",
    text: "Praticamente 1 mês utilizando o CDB oil e os benefícios são incríveis, desde que comecei usar meu sono melhorou, a compulsão por álcool e drogas cessou, ajudou também eu meu foco com as atividades diárias.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXgafsPe-Svdn79b8Lz8PsYtFXT9pHwmExjjIrtHuDI6SWGfk2J5g=s96-c-rp-mo-br100",
    tags: ["Insônia", "Foco"],
    publishedAt: "2026-04-20",
  },
  {
    name: "Cilene Frias",
    text: "Hoje faz um mês que iniciei meu tratamento com a click cannabis Me sinto outra pessoa Consigo dormir bem, sono tranquilo e sempre na paz com a minha mente . Melhor escolha tratamento com a click cannabis",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLI5JPcDNh-dHUSoiIo4mcZAg_qxDhClGVjVlGEENfiokHr8Q=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-05-12",
  },
  {
    name: "Vandir Villar",
    text: "Muito bom! Estou completando meu peimeiro mês de tratamento com Canabidiol. Meu sono está bem mais regularizado e também estou nitidamente menos impulsivo. Sem qualquer efeito colateral até o momento.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVzzUKfgzobitdJg4POQdir2pYVGoasamIKIYncKaY2qAylbLo8vg=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Impulsividade"],
    publishedAt: "2026-03-31",
  },
  {
    name: "Monica Cozendey",
    text: "Sofria com insônia, ansiedade e dores fortes nas pernas, hj sou uma nova pessoa graças a esse medicamento milagroso. Gostaria também de ressaltar o o atendimento impecável desta conceituada empresa.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXksb7km0T1nhQleHOsjVXjFzodLQReHUHyV5plO-4-HdjABEIGtQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Dor"],
    publishedAt: "2024-09-06",
  },
  {
    name: "Oliver Yassuo",
    text: "Anos de insônia estão sendo curados com este medicamento, e a ansiedade também deu uma bela controlada em paralelo. Eficaz e não tem efeitos colaterais. Indico a todos que sofrem dos mesmo problemas.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjX7krypOQAR6bRSMHFN6eoLvvAmG2zwQtK6UBwP_eeM8ZqLsRvBlw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-08-19",
  },
  {
    name: "João Paulo dos Santos",
    text: "Comecei o tratamento a poucos dias, mas já senti uma melhora na ansiedade que sentia e na insônia, também me sinto mas alegre e menos estressado, por enquanto o tratamento está me surpreendendo",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWZGpTbl61gt_mxr8KKjzsLfqaEX2lIKLx4wKrrU46nJdEu0-ib=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Estresse"],
    publishedAt: "2026-01-18",
  },
  {
    name: "Ketlyn Gonçalves",
    text: "Tem sido um diferencial essa experiência, quantas coisas eu não conseguia enxergar por viver ansiosa, por estar exausta por não conseguir dormir. Continuo firme e feliz como cada dia evoluindo!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXuMn8JX1p87oA7ltWo6y8mMFAXDrrTb9W_GE2JoUQ7T0esVhiqlg=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-07-17",
  },
  {
    name: "Uri Pellegrini",
    text: "Um mês de uso e meu sono mudou drasticamente para melhor! ansiedade diminuiu bastante tb. Só tenho a agradecer o excelente trabalho da Click e dos profissionais que estão na linha de frente!!!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVlCZi4XZIsCTFVZChNOdP5KfbeeF1rTYNmi3bMdE7AZMJZjGftfw=s96-c-rp-mo-ba3-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-12-15",
  },
  {
    name: "Leonardo Zerlotti",
    text: "Caria dia que passa me sinto mais calmo, meu sono está regrado, minha mente tem foco. Surreal! Parabéns a clínica que faz esse trabalho muito importante. Suporte incrível do começo ao fim!!",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocI26xS_u80JvVq7jWrF7YR0eBMyGVEEeDXCugJXBvokH246ow=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Foco"],
    publishedAt: "2025-05-09",
  },
  {
    name: "Maria Eleonora Rabêllo",
    text: "Estou há apenas um mês fazendo uso do Canabidiol e já sinto melhoras significativas na dor crônica aue tenho há mais de 30 anos , e na qualidade do meu sono ! Viva a medicina canábica!!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXxCrQXPQKzhH1oRcXNRlUxlwu4wXyNjDO3vikG1Qwcd9-UdLGC=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2025-05-30",
  },
  {
    name: "Augusto Siqueira",
    text: "Gostei da experiência de poder ter acesso a esses medicamentos, minhas dores crônicas do ombro quebrado e operado diminuíram, tenho tido boas noites de sono e me sinto menos ansioso.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWzPkzhm0HYvLx5aKU5EfNJn0y1lMmtR_s97mNSxz6YGUNt_r4=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Dor"],
    publishedAt: "2025-03-28",
  },
  {
    name: "William Oliveira Olivera",
    text: "Bom, primeiro mês ainda não sei dizer quais os efeitos positivos ou negativos, mas oque posso dizer é que em relação ao sono tem melhorado, na questão de acordar várias vezes a noite",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocI47hrh77PscUeweEspNaMTIsaZKQ4L-RQ4ifySZ3veRdnL8g=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-09-10",
  },
  {
    name: "Alessandra Rodrigues",
    text: "Comecei a dormir melhor e estou mais animada pra fazer as coisas qt a minha doença Aida não percebi nada de melhora mais só estou tomando a uma semana acho que é cedo pra falar",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocJ3jZGlQ4ge117hEnUgxeWaeFXLQSmXsgDmHldfLU0K6N9T3w=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-02-27",
  },
  {
    name: "Cleonice Candida moreira",
    text: "Comecei tem pouco tempo. Estou avaliando melhor o meu caso de insônia e do TDAH do meu filho. Quando nosso corpo tiver acostumado e os sintomas desaparecidos volto a falar.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLigQe-ywYMODRuq9ld4FxwuPQiZjB9LOZDuUZ9kHrgVrntKg=s96-c-rp-mo-br100",
    tags: ["Insônia", "TDAH"],
    publishedAt: "2024-10-02",
  },
  {
    name: "lu maia",
    text: "Estou gostando bastante, precisei aumentar a dose aos poucos, como foi recomendado e estou conseguindo dormir melhor...acredito que logo, conseguirei dormir a noite toda🙏🌿",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXy_M5EdkJKcPjyAVwCMiq0s8LmXeLmvqPcxAZC8WsavFfSec5S=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-10-09",
  },
  {
    name: "Cledir Schock",
    text: "Hoje meu tratamento completa 30 dias, a ansiedade sumiu, a compulsão por doces zerou, somente minha insônia ainda não cedeu mas vou chegar lá. Obrigada Click Cannabis ❤️",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLjfgfyobqbSgrkW8iynHkRIbemp69i6fdvKtn-VxCDMFo8tA=s96-c-rp-mo-ba4-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-07-16",
  },
  {
    name: "Fabio sá",
    text: "Produto excelente: comecei o tratamento no dia 14 de janeiro e realmente faz efeito. Importante ressaltar que estou usando a medicação para insônia e ansiedade. Ivone",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUxJ_u58vqMcACwYhbnIVkjC5YWjtPEz6_XOCH9sVRiZcjQVlKK=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2026-01-27",
  },
  {
    name: "Michael Marocco",
    text: "A utilização do CDB mudou meu bem estar. Hoje tenho qualidade do sono e minhas dores estão controladas, além de ter reduzido minha ansiedade. Eu mais que recomendo..",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLvJqy622MuxXmupi8xy7erTnCjDZPvb7CRgoHsSSFXe_lOyg=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Ansiedade", "Dor"],
    publishedAt: "2025-06-06",
  },
  {
    name: "Sergio Faria Jr",
    text: "Consulta com valor acessível. O médico que me atendeu foi muito atencioso. O tratamento está dando super certo para depressão, ansiedade e insônia. Super recomendo.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjURUJtf4S8OPDpB_n3gZ2u3pY9CjDTLlhqpPdqU5D9S7fBeg_siSA=s96-c-rp-mo-ba4-br100",
    tags: ["Insônia", "Ansiedade", "Depressão"],
    publishedAt: "2024-08-29",
  },
  {
    name: "Jhunyor Psicólogo",
    text: "Atendimento excelente e extremamente acolhedor. O produto é incrível, consegui eliminar os medicamentos que fazia uso para insônia e ansiedade. Recomendo a todos!!!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWHq_3bRPlvNHdb9jpzzWyXKjYWyXH-awTL7TmJCt4xYuwa7i9B-A=s96-c-rp-mo-ba4-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-01-21",
  },
  {
    name: "Meire Marinho",
    text: "Ainda estou no começo do tratamento de insônia e ansiedade, meu cérebro está se adaptando. A ansiedade (taquicardia) agora só às vezes 🙌 e estou dormindo bem melhor",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUUx2NAFdd_spdHWumkNkADai-8HjyI8gVwvr50FA6Qaixm2kS0fw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Pânico"],
    publishedAt: "2025-09-15",
  },
  {
    name: "Eduarda Carolini",
    text: "Depois de uma semana tomando o cbd senti uma melhora significativa na qualidade do meu sono e também sinto uma diminuição significativa na ansiedade do dia a dia.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjX6iRpogMUSIL_AIa4U25e-2wu6XusB9daFoe7NTpmWwgs_CThk=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-02-12",
  },
  {
    name: "angela maria carvalho silva cassol",
    text: "Estou melhorando meus sintomas, acredito que vou melhorar mais pois tomo uma dose bem pequena. Melhorou minha disposição e meu humor e a qualidade do sono .",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXVk9JrIcs7O1QT5QLgQamooUWqtE1H5SPIZ3bEeaidwqzl4UTukw=s96-c-rp-mo-ba4-br100",
    tags: ["Insônia", "Humor"],
    publishedAt: "2025-07-07",
  },
  {
    name: "Ricardo Andrade",
    text: "Excelente, já no primeiro mês de tratamento uma melhora significativa. Sono melhor, diminuindo o stress e já focando em meus afazeres. Gostando muito.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVGV5BiU_yQSDEKpRwVFkblOMeADiRsWzLNUBFqsH0Cmbjg6L7tew=s96-c-rp-mo-ba3-br100",
    tags: ["Insônia", "Estresse", "Foco"],
    publishedAt: "2025-05-05",
  },
  {
    name: "Marcio Sousa Rodrigues",
    text: "Bom dia. Medicamento do dia 20 gotas estabilizou. Medicamento da noite , ainda fazendo teste. Está com 20 gotas , mas o sono está instável. Obrigado",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocKOn8E1HRhkaM4hICPJwK1iCYxcELEOEJ9gxcG26u2FU0YfhA=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-05-28",
  },
  {
    name: "Alex Silva",
    text: "Meu tratamento está ainda no começo, mas já senti o potencial enorme que vai ser muito bom! Já senti da diferença principalmente na parte da insônia!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVUcLJnQVwIbQpnaPuJZH1iUvqMGfZVaeHys4WqRTn7G6q-XycR0w=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-03-06",
  },
  {
    name: "Brenda Iochem",
    text: "estou há uma semana fazendo o uso do óleo e já vi muita melhoria no meu sono, mais facilidade para dormir e vi muita melhora na minha irritabilidade",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjV6gnFbMUtCIaqaiUyEfxe75NIURRJJ2IYf29GQkgbvP6ihvymP=s96-c-rp-mo-br100",
    tags: ["Insônia", "Irritacao"],
    publishedAt: "2025-02-24",
  },
  {
    name: "Keysa Secatti",
    text: "Experiência do consumidor excelente, e eficácia da medicação ainda estamos avaliando. A medicação está sendo ministrada para dor crônica e insônia.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocKmb1W7bQGUy27HARKDpykalJnzmXbR-wHEp4Jssr8P65S42g=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2025-12-10",
  },
  {
    name: "Alexsandro Araujo",
    text: "Maravilhoso o tratamento! Meu sono tem melhorado 100% sem efeitos colaterais do medicamento! Eu tomava alprazolam pra dormir e agora não tomo mais!",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocJD332SO_yt02QvvIAHO_KuqDo4s6Xgqwe0ExiVGDRjaZTicw=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-11-03",
  },
  {
    name: "Fábio Veras",
    text: "Eu posso dizer que o canabidiol mudou a minha vida, nao tomo mais antidepressivo, durmo melhor, a qualidade de vida é outra, so tenho a agradecer.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocKD1xbzzbJYdnlSG9ADJD4pW5u_pHYrBAaP5LRCSUz3lJivyg=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia", "Depressão"],
    publishedAt: "2024-10-02",
  },
  {
    name: "Kelven Bittencourt",
    text: "Depois de uma semana, os resultados estão aparecendo, já consigo dormir melhor, os picos de estresse e ansiedade diminuíram, tem sido maravilhoso",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjV7q0fTIWUaaO_90vcrRXCVYTB-_gN3T5PdRUHThzgPNj5eZMaGeg=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Estresse"],
    publishedAt: "2025-03-04",
  },
  {
    name: "Ana Karina Santos",
    text: "Senti um melhora no meu sono com o gummy, eu acordava muito durante a noite e atualmente percebi que tenho dormido melhor e acordando bem menos.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocKCSkUrHY9d1hBQ5lB2SFy262nP9J2XKuYdtHop8dtS0Qm0Fw=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-05-09",
  },
  {
    name: "Elizangela Barbara Moraes",
    text: "Tem me ajudado muito a controlar a insônia, e as dores articulares diminuíram e ainda não estou na dose máxima recomendada. Recomendo a todos !",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWLzBm6jeRBUAAq_zMjQO2NslgewbgxiCH42Vk4POczVLLIC4_X8g=s96-c-rp-mo-br100",
    tags: ["Insônia", "Artrite", "Dor"],
    publishedAt: "2025-05-22",
  },
  {
    name: "Lipe diogenes silva",
    text: "estou satisfeita, me sentindo melhor, consigo dormir a noite toda , desde o início do tratamento, a equipe muito atenciosa, excelente feedback.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocLFMtu5TOA9tpqJIyJ4fzaI8MM72-1J8akjCvhG9KCd4QWp9w=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2026-01-12",
  },
  {
    name: "Ricardo marin",
    text: "estou usando a 30 dias. percebi que meu sono melhorou, estou mais tranquilo, e a dor no meu quadril que foi a minha reclamação dimunui bastente",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVwtUc85-y1HiZJZIpVGlSvUWC_8AE1oHONCdazLzdNKdcbDoQO=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2026-01-14",
  },
  {
    name: "Wadson Brito",
    text: "Depois que comecei o tratamento, a ansiedade diminuiu, o sono está se ficado regular e as dores que sentia com frequência diminuíram bastante",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWyXKKuUWjHbhJdPtJExyrQ6z50Bx92SlPhfGdwfRjpiUPNXuez=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Dor"],
    publishedAt: "2026-04-02",
  },
  {
    name: "Jheryk Marx",
    text: "Estou muito satisfeito pelo tratamento Consigo ter uma qualidade de sono melhor Até o meu humor melhorou Melhor qualidade de vida 🙂‍↔️😌",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjV4Ifms2UBQtBbom5W98h0SEDNfxEwOENuci2LVNo3_HUe-hahk=s96-c-rp-mo-br100",
    tags: ["Insônia", "Humor"],
    publishedAt: "2026-04-01",
  },
  {
    name: "Júlia Peixoto",
    text: "Eu estou me sentindo ótima com o medicamento, estou muito mais tranquila, calma, durmo muito melhor, e nunca mais tive enxaqueca!! Amei",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUaHwAYCsKT1Ya2O4huRIezAeLvgllJ0bM97POJ9cz3PPgoPX9s=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Enxaqueca"],
    publishedAt: "2024-04-19",
  },
  {
    name: "Vinicius Rodrigues",
    text: "Me sinto bem melhor, estou reduzindo o consumo de cerveja, sinto menos dores e estresse no dia a dia, e com mais qualidade no sono ...",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUPKpbuxcPnHK497X74DUFTZjcQPB3Oe21upybboCTnxjXS3Hl9=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor", "Estresse"],
    publishedAt: "2025-01-23",
  },
  {
    name: "Bruno Assis",
    text: "Meu sono melhorou muito estou fazendo uso a 15 dias, ainda em adaptação z porém, já consigo perceber algumas mudanças positivas.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjV8a3ycy14q2dR3IqPLGAVKQHjlu16xl3KxCbCZrWgLrboOv3mcZA=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia"],
    publishedAt: "2026-04-07",
  },
  {
    name: "Newton Alexandre Chaves de Souza",
    text: "Eu me senti bem melhor a insônia diminuiu bastante a vontade de fumar cigarro tb e a disposição melhorou bastante",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocL-QYAtFFuuEpChP9WYrELEcet5UcfTAH6Go1peTJERgHAfgg=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-09-12",
  },
  {
    name: "Ana Marta de Moraes Lopes",
    text: "Está sendo muito bom, já consigo dormir uma noite inteira, e diminuiu a ansiedade e a dor nas articulações. Muito obrigado 🙏😊",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUSMtgJZVdd5XTVVNaVnGQdP6l9Z4D4htsoJREMEMwPga5yO85FZA=s96-c-rp-mo-ba3-br100",
    tags: ["Insônia", "Ansiedade", "Artrite"],
    publishedAt: "2025-09-29",
  },
  {
    name: "Lauro Bezerra",
    text: "Experiência muito melhor que com os médicos com as prescrições tradicionais. Melhor remédio para insônia e dor que existe...",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUDQu3QfxVFrZmoaGCSmVWL1aPxxZtQ9o0QXm7DjvSV0OZMj4S6=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2024-08-21",
  },
  {
    name: "Katiany Vilarinho",
    text: "Estou bem no inicio do tratamento mas tenho percebido que consigo relaxar mais porque tenho uma noite de sono muito agitada.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjX-mWO_RAomyqtGzVyDLPZl11ZiJKM3lbOQ9KhE2m6lVU9ChIErgA=s96-c-rp-mo-ba4-br100",
    tags: ["Insônia"],
    publishedAt: "2024-04-05",
  },
  {
    name: "Lucia Ruas vilas boas",
    text: "Ainda recente o uso do medicamento! Mas percebo uma leve melhora! na anciedade,no sono e uma leve melhora na fibromialgia!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWaJDH2MBKCGWI4ruClaJCah4MO772LSIw8RWuGXxspnjat7xo9kw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Fibromialgia"],
    publishedAt: "2026-04-03",
  },
  {
    name: "Clemilson Gomes Melo Gomes",
    text: "Eu estou ficando bem melhor em algum requisito meu sono tá bem melhor,e eu recomendo para aqueles que querem se tratando.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjW93F4KMqi_aFxd7G--6tMFgOYX0yL4-KNZfVAS-x4rdKJIx_rXBg=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-05-05",
  },
  {
    name: "Lucas Braz",
    text: "Já estou me sentindo bem melhor! Menos ansiedade e parei de usar remédios tarja preta pra dormir! Sono melhorou muito!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWqJG4fZ_CKto2SqBNRyr6U0o3m2P_5q0v7HDoW_76HG0L94W2Zmw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2026-03-31",
  },
  {
    name: "Eliseu plauth",
    text: "o tratamento está ajudando bastante meus quadros de humor está ficando mais normalizados e meu sono está impecável",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocIeLTR4LuvAAsBaJf8fKsKN6gMKnx7xFTWuJoozO4XOJufbuQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Humor"],
    publishedAt: "2025-05-07",
  },
  {
    name: "Evaldo queiroz",
    text: "Com um mês de tratamento minha vida deu uma melhora muita boa. Voltei a dormir bem e as dores estão quase sumindo.",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocItsQRoOWKJVX6pOrRzyYrg0bd_PDXSsk8TelhGZd6U-3T9lQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2025-05-23",
  },
  {
    name: "Roseni Santos",
    text: "Tem sido maravilhoso, sono mais tranquilo, concentração foco na atividades e principalmente ansiedade controlando",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocIytM6anLTjR4AxVqyAKHpbgPTB8i_q8dkSykprak6xnfCCJQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Foco"],
    publishedAt: "2025-09-03",
  },
  {
    name: "Rafael Dionísio",
    text: "Foi ótimo me sentindo menos ansioso estou mais tranquilo ótimo para l sono dei até para minha esposa ela adorou",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocICaEjc2DCMrHAemVuoGTHw3ua5A1NHVpraFj-nNeUACu4=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-08-20",
  },
  {
    name: "RENAN ARRUDA",
    text: "Muito bom! Meus picos de ansiedade durante o dia e minhas noites de sono graças a Deus estão controlados. Paz!",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocIepX_m1vmSAOYc7iGT-xZBH9Ks9lHSD5MIsVhLFXKgM-BEycXs=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Pânico"],
    publishedAt: "2026-02-12",
  },
  {
    name: "Jeni Lisbeth",
    text: "Estou há um mês usando, tenho percebido que estou menos dolorida, durmo bem, tenho mais foco e menos ansiedade",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUaW_vj-4ik-P3zypRUryxJaYAhTC2sAvN9YUiN3f6cZC6mEGYhRw=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade", "Dor"],
    publishedAt: "2025-03-10",
  },
  {
    name: "Sandra Araujo",
    text: "Olá. Hj é o meu 4o dia de uso. Meu sono melhorou bastante, tenho dormido bem! Espero qualidade de vida melhor!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVRr_xHhmvdHdYru1-a7mpHGmgltUSF5ECY2kZdMysJRoWl-FQl_g=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2026-02-14",
  },
  {
    name: "Lucimara Amandio",
    text: "Já senti muita diferença em 30 dias de tratamento,minhas dores ficaram mais amenas e o sono melhorou muuuito!",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVtALnXWfU0egQCoLSVWfokAqZKm760g61lt9hKPaDhvsrNUewEnQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2025-05-28",
  },
  {
    name: "kevin ribeiro",
    text: "Até o momento está sendo incrível, boa parte da minha ansiedade reduziu e meu sono está cada vez melhor",
    photo: "https://lh3.googleusercontent.com/a/ACg8ocKDrcz2uycaxtycE4IsXyz7fpztRmBdRvBwABzxOCdsI0OeQQ=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-05-10",
  },
  {
    name: "Suelen Moiano",
    text: "Eu estou gostando muito estou mais estou conseguindo dormir melhor e a ansiedade estou controlada.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWGRbmHhnySiIF4AZXHUh5Yy-zJARu8cXoM606hXOZPX4E4Hl0zvg=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-05-15",
  },
  {
    name: "Alan Paulo Moura",
    text: "Gente eu gostei muito . No meu caso era só um ajuste p higienizar o meu sono e está funcionando",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWW8bUAU-fTlsyACs70PbFHSrH1M5kFrjgWpdQzzWS16ugckxJ2Iw=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2026-02-09",
  },
  {
    name: "Natã Bernardo",
    text: "Já senti uma grande diferença na qualidade do sono e a ansiedade está um pouco mais controlada.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUcUSkZ0VHm1E_CIxiGjV4q-T4ZUgUuJOPnwDx_Uucn2NL1b9U=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-03-04",
  },
  {
    name: "Leandro Bernardo",
    text: "Melhora significativa na ansiedade e qualidade do sono depois que comeceia a usar o CDB .",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVggF7H9d6_bUeTk1IDku68AeL49Yw5ylgEt-mytWuDFqyXfzad0Q=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2026-04-07",
  },
  {
    name: "Lizandra Barbuto",
    text: "Atendimento super humano, o tratamento esta me ajudando muito na insônia da menopausa.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjV5PL9zz5LzifdSd5c98lZmndICVeDGcT8hGWVMBvHDhqSAN1pmow=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2026-01-27",
  },
  {
    name: "Ande",
    text: "Maravilhoso viver livre de dores. Estou mais disposta, durmo melhor. Depressão foi se.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjX6RY1dO_JW9bN_-k3J6xArynL4tK02_bDen-OMF2grHrp_on0=s96-c-rp-mo-br100",
    tags: ["Insônia", "Depressão", "Dor"],
    publishedAt: "2026-01-21",
  },
  {
    name: "ROBERTA VALERIA DE MORAES MARCELINO",
    text: "Excelente resultado, hoje eu consigo dormir melhor e não sinto dores como antes",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWySwKl6exv5Cu5MTegyml4gvAq42rz68mlcSjrrM04X1kNd3M=s96-c-rp-mo-br100",
    tags: ["Insônia", "Dor"],
    publishedAt: "2025-09-22",
  },
  {
    name: "Edson Botelho",
    text: "Tá sendo incrível mudou minha vida trabalho sono desempenho 100% a mais agora",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVUSzjyqndvn5Jidba-Og8obrzsDICSYqrX4aOXfmoXcjEz7e7N=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-10-03",
  },
  {
    name: "Luiz Monteiro",
    text: "To bem no início e já estou com 90% do resultado para insônia. Gostei",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjX73f0JCC4BLWucKNdPeflgoYDrUtThX1pwfVCwcDypq6Vj1o3l=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-05-06",
  },
  {
    name: "Davi Amorim",
    text: "Excelente produto, eficiente e, está mudando o meu sono para melhor…",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjULu-4PSjENgC6VIG3eB9KnYBuZl5gpmqrtBfOqhB4gb8cpZczglA=s96-c-rp-mo-ba2-br100",
    tags: ["Insônia"],
    publishedAt: "2026-04-28",
  },
  {
    name: "Rai Freitas",
    text: "A qualidade do sono melhorou muito em um mês de tratamento,recomendo",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjUrtDFXuSWkXk3Ly8xMWhNQdMxpa9VSS-JFLnC0CpANtQ0TwR-l=s96-c-rp-mo-ba4-br100",
    tags: ["Insônia"],
    publishedAt: "2025-09-12",
  },
  {
    name: "jaiede nicacio",
    text: "Melhora do sono bem importante. Resultados logo na primeira semana",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXtIot3OhEJDzYqnjMX3A1EB89lcJIqRMFqcnPnQ1cwAbgTYwo=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-09-19",
  },
  {
    name: "Roger Net",
    text: "Durante a primeira semana de tratamento meu sono melhorou bastante",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjXG0QYLbHoCHSbOoMZwP2n5u2F6RIiHeUSosEmpQGGKhCA3zZFqVg=s96-c-rp-mo-ba3-br100",
    tags: ["Insônia"],
    publishedAt: "2025-01-21",
  },
  {
    name: "nelson santos",
    text: "Em uma semana consigui perceber uma melhora no meu sono e humor",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjVIi-cUrfee0-RYYOqV5BRX8VGYZoX7qP7tSkTtAg_H1ReoMAtY=s96-c-rp-mo-br100",
    tags: ["Insônia", "Humor"],
    publishedAt: "2025-02-12",
  },
  {
    name: "Alysson Teixeira",
    text: "Um mês de tratamento e percebi que meu sono está bem melhor.",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjWQznws4mWwWrUTKoxztg7EtezDQQKIDwSzdYTJOKN8oauSXBoI=s96-c-rp-mo-br100",
    tags: ["Insônia"],
    publishedAt: "2025-09-19",
  },
  {
    name: "Guilherme Leite Coura",
    text: "Tô gostando e tá auxiliando na qualidade de sono e ansiedade",
    photo: "https://lh3.googleusercontent.com/a-/ALV-UjX3l9J2I0maA0MEXQQfb1a9ypCWOvgprhjeprlwXjVvLG7DeKBG=s96-c-rp-mo-br100",
    tags: ["Insônia", "Ansiedade"],
    publishedAt: "2025-06-30",
  },
];
